### ISSUE TITLE
OAuthService RefreshUserTokenRestRequest GuzzleHttp Exception

### ISSUE THREAD

**Issue by smartinec** [davidtsadler/ebay-sdk-php#155]
Getting this uncaught exception if the refresh token goes bad:

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: 'POST https://api.ebay.com/identity/v1/oauth2/token' resulted in a '400 Bad Request' response:
{"error":"invalid_grant","error_description":"the provided authorization refresh token is invalid or was issued to anoth (truncated...)
 in vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 vendor/guzzlehttp/promises/src/TaskQueue.php(47 in vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

**Comment by smartinec** [comment]
As a work-around, I set `httpOptions => http_errors = FALSE` and used this to catch the error `$response->getStatusCode() == 400 && $response->error == 'invalid_grant'`. It seems like this should be the default setting since eBay is returning a valid response object.
