### ISSUE TITLE
Cannot read credentials from /.ebay_sdk/credentials

### ISSUE THREAD

**Issue by kossmokvin** [davidtsadler/ebay-sdk-php#206]
Hello,
I have just installed the SDK on hosting and tried to run the first example. But there is a problem - i am getting a error 500.

This step is causing the problem:
$service = new Services\ShoppingService();

Tried 5.5, 5.6, 7.0 and 7.1 PHP versions.

Please help

Apache Log:
```
Mon Jul 02 19:45:25.848029 2018] [cgi:error] [pid 17056] [client 107.181.175.49:48642] AH01215: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Cannot read credentials from /.ebay_sdk/credentials' in /home/rainbowd/domains/raindrop.pro/public_html/vendor/dts/ebay-sdk-php/src/Credentials/CredentialsProvider.php:132: /php56bin/rainbowd/php-cgi
[Mon Jul 02 19:45:25.848079 2018] [cgi:error] [pid 17056] [client 107.181.175.49:48642] AH01215: Stack trace:: /php56bin/rainbowd/php-cgi
[Mon Jul 02 19:45:25.848217 2018] [cgi:error] [pid 17056] [client 107.181.175.49:48642] AH01215: #0 /home/rainbowd/domains/raindrop.pro/public_html/vendor/dts/ebay-sdk-php/src/Credentials/CredentialsProvider.php(82): DTS\\eBaySDK\\Credentials\\CredentialsProvider::DTS\\eBaySDK\\Credentials\\{closure}(): /php56bin/rainbowd/php-cgi
[Mon Jul 02 19:45:25.848356 2018] [cgi:error] [pid 17056] [client 107.181.175.49:48642] AH01215: #1 /home/rainbowd/domains/raindrop.pro/public_html/vendor/dts/ebay-sdk-php/src/Credentials/CredentialsProvider.php(56): DTS\\eBaySDK\\Credentials\\CredentialsProvider::DTS\\eBaySDK\\Credentials\\{closure}(): /php56bin/rainbowd/php-cgi
[Mon Jul 02 19:45:25.848489 2018] [cgi:error] [pid 17056] [client 107.181.175.49:48642] AH01215: #2 /home/rainbowd/domains/raindrop.pro/public_html/vendor/dts/ebay-sdk-php/src/functions.php(84): DTS\\eBaySDK\\Credentials\\CredentialsProvider::DTS\\eBaySDK\\Credentials\\{closure}(): /php56bin/rainbowd/php-cgi
[Mon Jul 02 19:45:25.848603 2018] [cgi:error] [pid 17056] [client 107.181.175.49:48642] AH01215: #3 /home/rainbowd/domains/raindrop.pro/public_html/vendor/dts/ebay-sdk-php/src/ConfigurationResolver.php(59): DTS\\eBaySDK\\applyCredentials(Object(Closure), Array): /php56bin/rainbowd/php-cgi
[Mon Jul 02 19:45:25.848716 2018] [cgi:error] [pid 17056] [client 107.181.175.49:48642] AH01215: #4 /home/rainbowd/domains/raindrop. in /home/rainbowd/domains/raindrop.pro/public_html/vendor/dts/ebay-sdk-php/src/Credentials/CredentialsProvider.php on line 132: /php56bin/rainbowd/php-cgi
```

**Comment by michabbb** [comment]
ehm... you know github has a nice function called "[SEARCH](https://github.com/davidtsadler/ebay-sdk-php/blob/3584f5fa985386b392b178d1b4212b6770dbc547/src/Credentials/CredentialsProvider.php#L132)" ?? it´s really nice, you should try this, it works like a mirical sometimes. and there are a lot of [examples](https://github.com/davidtsadler/ebay-sdk-examples).

**Comment by michabbb** [comment]
btw.. why don´t people never close their issues... i will never understand this... 🤔

**Comment by kossmokvin** [comment]
Because they do not use Github regulary and leave the website after downloading source or not getting the answer on issue. Sad but true =P
Good luck and thank you for try )

**Comment by Suhail-Mansoori** [comment]
mera demmag kharab ho gya h sala api nhi lg rhi h ebay ki

**Comment by michabbb** [comment]
@Suhail-Mansoori gaay bahut jyaada khaatee hai isalie chandrama ko girana padata hai aur traiphik lait haree dikhatee hai
